id_field = '_id'
title_field = 'title'
site_name_field = 'site_name'
parse_date_field = 'parse_date'
publish_date_field = 'publish_date'
article_url_field = 'article_url'
youtube_url_field = 'youtube_url'
description_field = 'description'
is_video_field = 'is_video'
image_url_field = 'image_url'

image_type_field = 'image_type'
ml_label_field = 'ml_label'
batch_id_field = 'batch_id'
etl_dttm_field = 'etl_dttm'
contains_content_field = 'description_contains_content'
