FROM ubuntu:14.04
MAINTAINER Vanessa Feng <vanessa.w.feng@gmail.com>

RUN apt-get update

# install useful system tools and libraries
RUN apt-get install -y libfreetype6-dev && \
    apt-get install -y libglib2.0-0 \
                       libxext6 \
                       libsm6 \
                       libxrender1 \
                       libblas-dev \
                       liblapack-dev \
                       gfortran \
                       libfontconfig1 --fix-missing

RUN apt-get install -y tar \
                       git \
                       curl \
                       nano \
                       wget \
                       dialog \
                       net-tools \
                       build-essential

RUN apt-get install -y python \
                       python-dev \
                       python-distribute \
                       python-pip \
                       python-numpy \
                       python-scipy


# complete Python image
RUN useradd -d /app -m app
RUN chown -R app:app /app/

