FROM kllect:python_code
MAINTAINER Vanessa Feng <vanessa.w.feng@gmail.com>

# copy over config
COPY ./config /app/config
RUN chown -R app:app /app/


# Deploy service configuration
RUN cp /app/config/supervisord/supervisord.conf /etc/
RUN mkdir -p /etc/supervisord/conf.d/
RUN cp /app/config/supervisord/apps.conf /etc/supervisord/conf.d/

#Expose ports and start supervisord
EXPOSE 5011
CMD ["supervisord", "-n"]
#WORKDIR /app/src
#CMD ["python", "main.py"]
