VERSION = 1.01

CLASSIFICATION_PORT = 8080

CATEGORY_CLASSIFICATION_ROUTE = 'category_classification'
CONTENT_CLASSIFICATION_ROUTE = 'tag_classification'
FULL_CLASSIFICATION_ROUTE = 'full_classification'

